import { describe, expect, it } from 'bun:test'
import fs from 'node:fs/promises'
import path from 'node:path'
import * as day8 from '../src/day08'

describe('d8:p1', () => {
  it('should solve the example input', () => {
    const input = `
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............`

    expect(day8.part1(input)).toEqual(14)
  })

  it('should solve the puzzle input', async () => {
    const input = await fs.readFile(
      path.resolve(__dirname, '../input/day08.txt'),
      'utf-8',
    )
    expect(day8.part1(input)).toEqual(256)
  })
})

describe('d8:p1', () => {
  it('should solve the example input', () => {
    const input = `
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............`

    expect(day8.part2(input)).toEqual(34)
  })

  it('should solve the puzzle input', async () => {
    const input = await fs.readFile(
      path.resolve(__dirname, '../input/day08.txt'),
      'utf-8',
    )
    expect(day8.part2(input)).toEqual(1005)
  })
})
